#!/usr/bin/env python3
"""Evaluate verification and repair outputs."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from tsr.utils.io import read_jsonl, write_json, write_text
from tsr.verification.metrics import (
    claim_retention_rate,
    claims_per_explanation,
    summarize_generation_cost,
    summarize_verification,
    supported_claim_preservation,
)


def _resolve(path: str) -> Path:
    p = Path(path)
    return p if p.is_absolute() else ROOT / p


def _flatten(records, field):
    results = []
    for record in records:
        results.extend(record.get(field, []))
    return results


def _latex_metric_table(metrics: dict) -> str:
    before = metrics.get("before_repair", {})
    after = metrics.get("after_repair", {})
    return r"""\begin{table}[t]
\centering
\small
\begin{tabular}{lrrrrrr}
\toprule
Setting & ClaimFaith. $\uparrow$ & Unsup. Rate $\downarrow$ & Partial Rate & Claims/Expl. & Cost/Expl. & Claims \\
\midrule
Before Repair & %(bf).3f & %(bu).3f & %(bp).3f & %(bcpe).2f & %(cpe).5f & %(bn).0f \\
After Repair & %(af).3f & %(au).3f & %(ap).3f & %(acpe).2f & %(cpe).5f & %(an).0f \\
\bottomrule
\end{tabular}
\caption{Automatic verification summary generated by \texttt{scripts/evaluate.py}. Claim retention is %(ret).3f and supported-claim preservation is %(pres).3f.}
\label{tab:auto-summary}
\end{table}
""" % {
        "bf": before.get("claim_faithfulness", 0.0),
        "bu": before.get("unsupported_claim_rate", 0.0),
        "bp": before.get("partial_support_rate", 0.0),
        "bcpe": before.get("claims_per_explanation", 0.0),
        "bn": before.get("n_claims", 0.0),
        "af": after.get("claim_faithfulness", 0.0),
        "au": after.get("unsupported_claim_rate", 0.0),
        "ap": after.get("partial_support_rate", 0.0),
        "acpe": after.get("claims_per_explanation", 0.0),
        "an": after.get("n_claims", 0.0),
        "cpe": metrics.get("cost", {}).get("cost_per_explanation_usd", 0.0),
        "ret": metrics.get("claim_retention_rate", 0.0),
        "pres": metrics.get("supported_claim_preservation", 0.0),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", default="outputs/evaluation_metrics.json")
    args = parser.parse_args()

    records = read_jsonl(_resolve(args.input))
    before = summarize_verification(_flatten(records, "verification_results"))
    after = summarize_verification(_flatten(records, "repaired_verification_results"))
    before["claims_per_explanation"] = claims_per_explanation(int(before["n_claims"]), len(records))
    after["claims_per_explanation"] = claims_per_explanation(int(after["n_claims"]), len(records))
    metrics = {
        "input": args.input,
        "n_records": len(records),
        "before_repair": before,
        "after_repair": after,
        "claim_retention_rate": claim_retention_rate(int(before["n_claims"]), int(after["n_claims"])),
        "supported_claim_preservation": supported_claim_preservation(records),
        "cost": summarize_generation_cost(records),
    }
    output_path = _resolve(args.output)
    write_json(output_path, metrics)
    table = _latex_metric_table(metrics)
    write_text(ROOT / "outputs" / "tables" / "auto_summary.tex", table)
    print(f"Wrote metrics to {output_path.relative_to(ROOT)}")
    print(metrics)


if __name__ == "__main__":
    main()
